server:
  port: 8010    #port number

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://eureka-server.default.svc.cluster.local:8761/eureka}
    healthcheck:
      enabled: true
    lease:
      duration: 5

spring:
  application:
    name: api-gateway

management:
  security:
    enabled: false

logging:
  level:
    com.self.sprintboot.learning.apigateway: DEBUG